### PR TITLE
Parse data out of the promise object.

### LINKED ISSUE #75: Parse out data from promise objects from the server calls

### PR DESCRIPTION
**Pull request by johndavis92790**
- Clean up serverCalls.tsx
- Move test API calls to NavBar.tsx
- Change testAPICalls to work correctly with awaited promise objects to access the data properly.
- Remove category from Restaurant model as it is probably unneccessary.

### CODE REVIEW

**Review by Kimberly-Rodriguez — APPROVED** [review]
The only question I have is why are we using 'any' for most typescript notation. Wouldn't the restaurant_ ID be 'number'? Or do we not know the type?

**Comment by johndavis92790** [comment]
> The only question I have is why are we using 'any' for most typescript notation. Wouldn't the restaurant be number? Or do we not know the type?

Which line are you talking about exactly? I am putting `any` type on lots of things right now temporarily since we are so early in building things. We can refactor the types later after we have a better idea of how things are being used.

**Comment by Kimberly-Rodriguez** [comment]
> > The only question I have is why are we using 'any' for most typescript notation. Wouldn't the restaurant be number? Or do we not know the type?
> 
> Which line are you talking about exactly? I am putting `any` type on lots of things right now temporarily since we are so early in building things. We can refactor the types later after we have a better idea of how things are being used.

Got it. Also, there seems to be a merge conflict with the code, do you see the issue?

**Comment by Kimberly-Rodriguez** [comment]
>

**Comment by johndavis92790** [comment]
> > > The only question I have is why are we using 'any' for most typescript notation. Wouldn't the restaurant be number? Or do we not know the type?
> > 
> > 
> > Which line are you talking about exactly? I am putting `any` type on lots of things right now temporarily since we are so early in building things. We can refactor the types later after we have a better idea of how things are being used.
> 
> Got it. Also, there seems to be a merge conflict with the code, do you see the issue?

Yes I will take care of the merge conflicts tonight. Please don't close the PR until the branch has been merged into develop. In fact, if you are the reviewer of a PR, you should not close the PR or merge the branch because it's not your branch or your PR, does that make sense? You are only reviewing it.

**Review by Kimberly-Rodriguez — APPROVED** [review]

**Pull request merged**
